# Generated by Django 4.0.4 on 2024-05-30 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_alter_ticket_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airplane',
            name='rows',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='airplane',
            name='seats_in_row',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
