# Generated by Django 4.0.4 on 2024-06-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_alter_airplane_rows_alter_airplane_seats_in_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.ManyToManyField(blank=True, to='airport.crew'),
        ),
    ]
